# Generated by Django 5.2.8 on 2025-12-27 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_list', '0002_remove_fooditem_restaurant_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
