# Generated by Django 5.2.8 on 2025-12-01 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_auth', '0002_vendor_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='owner',
        ),
        migrations.AlterField(
            model_name='vendor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
